
package org.jack.app.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OneServiceService", targetNamespace = "http://webservice.app.jack.org/", wsdlLocation = "http://localhost:9999/one?wsdl")
public class OneServiceService
    extends Service
{

    private final static URL ONESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ONESERVICESERVICE_EXCEPTION;
    private final static QName ONESERVICESERVICE_QNAME = new QName("http://webservice.app.jack.org/", "OneServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/one?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ONESERVICESERVICE_WSDL_LOCATION = url;
        ONESERVICESERVICE_EXCEPTION = e;
    }

    public OneServiceService() {
        super(__getWsdlLocation(), ONESERVICESERVICE_QNAME);
    }

    public OneServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ONESERVICESERVICE_QNAME, features);
    }

    public OneServiceService(URL wsdlLocation) {
        super(wsdlLocation, ONESERVICESERVICE_QNAME);
    }

    public OneServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ONESERVICESERVICE_QNAME, features);
    }

    public OneServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OneServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OneService
     */
    @WebEndpoint(name = "OneServicePort")
    public OneService getOneServicePort() {
        return super.getPort(new QName("http://webservice.app.jack.org/", "OneServicePort"), OneService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OneService
     */
    @WebEndpoint(name = "OneServicePort")
    public OneService getOneServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.app.jack.org/", "OneServicePort"), OneService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ONESERVICESERVICE_EXCEPTION!= null) {
            throw ONESERVICESERVICE_EXCEPTION;
        }
        return ONESERVICESERVICE_WSDL_LOCATION;
    }

}
